In [ ]:
import numpy as np

In [ ]:
arr = np.arange(5,26)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [ ]:
rand = np.random.randint(10,51,size=(3,4))
rand


array([[18, 40, 36, 40],
       [44, 12, 34, 21],
       [28, 12, 29, 50]])

In [ ]:
arr.shape

(21,)

In [ ]:
arr.size

21

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
rand.shape

(3, 4)

In [ ]:
rand.size

12

In [ ]:
rand.dtype

dtype('int64')

In [ ]:
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 3, 5, 7, 9])

In [ ]:
arr1+arr2

array([ 3,  7, 11, 15, 19])

In [ ]:
arr1-arr2

array([1, 1, 1, 1, 1])

In [ ]:
arr1*arr2

array([ 2, 12, 30, 56, 90])

In [ ]:
arr1/arr2

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

In [ ]:
arr3 = np.arange(1,10)
arr3.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
result = arr3*5
print(result)

[ 5 10 15 20 25 30 35 40 45]


In [ ]:
arr4 = np.arange(10,26).reshape(4,4)
arr4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
print(arr4[1,:])
print(arr4[:,-1])

[14 15 16 17]
[13 17 21 25]


In [ ]:
arr4[0,:] = 0
arr4

array([[ 0,  0,  0,  0],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
arr5 = np.random.randint(20,40,10)
arr5

array([26, 31, 37, 31, 35, 35, 37, 23, 26, 24])

In [ ]:
arr5>30

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [ ]:
arr6 = np.arange(11,23).reshape(3,4)
arr6

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [ ]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
res = np.dot(mat1,mat2)
print(res)
res.T



[[19 22]
 [43 50]]


array([[19, 43],
       [22, 50]])

In [ ]:
arr7 = np.random.randint(10,60,15)
arr7
print(arr7.mean())

print(arr7.std())


37.86666666666667
12.451862868217306


In [ ]:
mat3 = np.array([[2,1,3],[0,5,6],[7,8,9]])
mat3
det = np.linalg.det(mat3)
print(det)
inverse = np.linalg.inv(mat3)
print(inverse)

-68.99999999999996
[[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
